### ISSUE TITLE
RuntimeError: cuda runtime error (2) : out of memory

### ISSUE THREAD

**Issue by z1412247644** [NVIDIA/FastPhotoStyle#11]
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1501969512886/work/pytorch-0.1.12/torch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
Traceback (most recent call last):
  File "demo.py", line 68, in <module>
    stylized_img = p_wct.transform(cont_img, styl_img, cont_seg, styl_seg)
  File "/home/boss/FastPhotoStyle-master/photo_wct.py", line 36, in transform
    sF4,sF3,sF2,sF1 = self.e4.forward_multiple(styl_img)
  File "/home/boss/FastPhotoStyle-master/models.py", line 393, in forward_multiple
    out1 = self.conv3(out1)
  File "/home/boss/anaconda2/envs/NVIDIA/lib/python3.5/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/boss/anaconda2/envs/NVIDIA/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 237, in forward
    self.padding, self.dilation, self.groups)
  File "/home/boss/anaconda2/envs/NVIDIA/lib/python3.5/site-packages/torch/nn/functional.py", line 40, in conv2d
    return f(input, weight, bias)
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1501969512886/work/pytorch-0.1.12/torch/lib/THC/generic/THCStorage.cu:66

**Comment by Yijunmaverick** [comment]
@z1412247644 Thanks for your interests. It looks like a GPU memory problem. Would you try to resize your input image first (smaller), in order to fit your GPU memory?

**Comment by z1412247644** [comment]
@Yijunmaverick Thank you for your answer. It's no longer a mistake, but there's a new problem.
##
RuntimeError: the number of sizes provided       must be greater or equal to the number of dimensions in the tensor at /opt/conda/conda-bld/pytorch_1501969512886/work/pytorch-0.1.12/torch/lib/THC/generic/THCTensor.c:299
##
Do you know how to solve it?  Thanks.

**Comment by Yijunmaverick** [comment]
@z1412247644 See [here](https://github.com/NVIDIA/FastPhotoStyle/issues/2) if it helps. I actually do not meet this error :)

**Comment by z1412247644** [comment]
@Yijunmaverick Thank you very much. My problems have been solved. You are wise and wise.

**Comment by verggil** [comment]
@Yijunmaverick could you please add some information about how large amount of video memory is needed for the demo run to the readme? It will be really helpful for understanding if it possible or not to run the app. 
I was a little confused, when I got "out of memory" on tesla k80 =)
Thanks in advance!

**Comment by matthewarthur** [comment]
I also receive the cuda runtime error. How large can the photos be? I am having to downgrade dramatically and the output is low quality. 

RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1512378422383/work/torch/lib/THC/generic/THCStorage.cu:58

**Comment by mingyuliutw** [comment]
For out of memory issue, we will continue the discussion on #27
