### ISSUE TITLE
Much Slower Than the Reported Time

### ISSUE THREAD

**Issue by onlywuyiwuyi** [NVIDIA/FastPhotoStyle#19]
Hi,
I tested your code by running demo.sh with a K40m GPU, but my CUDA version is 8.0 (not 9.1). The total time is about 145s, more than 10 times slower than the reported time in the paper (11.39s for 1K image size). Besides a better GPU (Titan XP), I wonder whether the new CUDA is the key for the high performance. Thanks.

**Comment by mingyuliutw** [comment]
Could your report the times for the 3 processing steps individually?

**Comment by onlywuyiwuyi** [comment]
Elapsed time in stylization: 2.512861
Elapsed time in propagation: 141.474549
Elapsed time in post processing: 1.093370

**Comment by Yijunmaverick** [comment]
@onlywuyiwuyi Did you install `scikit-umfpack` as suggested in USGAE.md?

pip install scikit-umfpack

**Comment by onlywuyiwuyi** [comment]
Thanks. By installing scikit-umfpack, the second stage is accelerated to 25s. Is this time reasonable?

**Comment by Yijunmaverick** [comment]
No idea about your image size and GPU specs, but I think it looks okay.
