### ISSUE TITLE
can't find vgg_normalised_conv1_1_mask.t7

### ISSUE THREAD

**Issue by albin3** [NVIDIA/FastPhotoStyle#23]
```
No such file or directory: './models/vgg_normalised_conv1_1_mask.t7'
```

is this the mask of content image?

**Comment by Yijunmaverick** [comment]
@albin3 Please download pre-trained [models](https://drive.google.com/file/d/1ENgQm9TgabE1R99zhNf5q6meBvX6WFuq/view) first, as stated in USAGE.md.

**Comment by albin3** [comment]
ok, thx
