### ISSUE TITLE
How to run the demo in CPU mode?

### ISSUE THREAD

**Issue by wusai80** [NVIDIA/FastPhotoStyle#27]
I noticed that the new version supports running WCT in cpu mode, but how? When I comment the code "p_wct.cuda(0)" or change is_cuda to always return false, I get the following errors. Any idea what to do?

ps: The demo runs well in GPU mode.
 
Elapsed time in stylization: 0.656382
Traceback (most recent call last):
  File "demo.py", line 40, in <module>
    output_image_path=args.output_image_path,
  File "/home/wusai/PycharmProjects/FastPhotoStyle/process_stylization.py", line 55, in stylization
    stylized_img = p_wct.transform(cont_img, styl_img, cont_seg, styl_seg)
  File "/home/wusai/PycharmProjects/FastPhotoStyle/photo_wct.py", line 35, in transform
    csF4 = self.__feature_wct(cF4, sF4, cont_seg, styl_seg)
  File "/home/wusai/PycharmProjects/FastPhotoStyle/photo_wct.py", line 78, in __feature_wct
    target_feature = self.__wct_core(cont_feat_view, styl_feat_view)
  File "/home/wusai/PycharmProjects/FastPhotoStyle/photo_wct.py", line 118, in __wct_core
    contentConv = torch.mm(cont_feat, cont_feat.t()).div(cFSize[1] - 1) + iden
  File "/usr/local/lib/python2.7/dist-packages/torch/tensor.py", line 305, in __add__
    return self.add(other)
TypeError: add received an invalid combination of arguments - got (torch.FloatTensor), but expected one of:
 * (float value)
      didn't match because some of the arguments have invalid types: (torch.FloatTensor)
 * (torch.cuda.FloatTensor other)
      didn't match because some of the arguments have invalid types: (torch.FloatTensor)
 * (torch.cuda.sparse.FloatTensor other)
      didn't match because some of the arguments have invalid types: (torch.FloatTensor)
 * (float value, torch.cuda.FloatTensor other)
 * (float value, torch.cuda.sparse.FloatTensor other)

**Comment by suquark** [comment]
Oops, it should be caused by :
https://github.com/NVIDIA/FastPhotoStyle/blob/f895e62ea156c7dc5886a87fdc21f61a79f9781c/process_stylization.py#L48-L49
Just remove those 'cuda(0)'. I will make a PR to fix it.
