### ISSUE TITLE
Are you guys presenting any talks/demos on this at GTC ?

### ISSUE THREAD

**Issue by borisfom** [NVIDIA/FastPhotoStyle#29]

**Comment by mingyuliutw** [comment]
Yes, I will talk about the algorithm in my GTC talk. I will also cover my other image translation work in the talk. Information of the talk is given below. For GTC registration discount, please use GMSGTC18. 

Unsupervised Image-to-Image Translation Networks
S8114  Talk
- Thursday, 3/29/18  |  15:00 - 15:50 - Grand Ballroom 220B

**Comment by borisfom** [comment]
Thanks for the info and good luck!
Are you planning to have any demos on the floor as well? 
It may not be too late to get in. If you are interested, please e-mail me :  bfomitchev at nvidia
