### ISSUE TITLE
Smoothing twice

### ISSUE THREAD

**Issue by wesleyw72** [NVIDIA/FastPhotoStyle#34]
Within the paper, I can only see smoothing mentioned once. However in the implementation smoothing is performed twice in photo_smooth.py and smooth_filter.py.

Am I misunderstanding the paper/implementation regarding the second smoothing technique, or is this an addition made? If so, can you explain why this was added?

**Comment by mingyuliutw** [comment]
Please check the experiment section for the following sentence 

> We also use the post-processing filtering step in Luan et al. [21] ...

The post-processing also smooths the image. That's why we call it smooth_filter in the code. This might be the source of confusion.

**Comment by Yijunmaverick** [comment]
Check section 5 [here](https://www.cs.cornell.edu/~fujun/files/style-cvpr17/style-cvpr17-supp.pdf) in [21].

**Comment by wesleyw72** [comment]
Thanks for your help, I had misunderstood. Mechrez et al. [22] experimented with training an image-to-image  Conditional Generative Adversial Network to apply the same effect as their smoothing step. 

I am interested to know if you tried anything similar? If not, do you have any views on that approach?
