### ISSUE TITLE
Running FastPhotoStyle on MacOS

### ISSUE THREAD

**Issue by fabulousrice** [NVIDIA/FastPhotoStyle#41]
Hi I'm a bit new to Python and have trouble understanding the messages I get when running "converter.py" in Terminal:

usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory

What am I supposed to do next? These don't seem to be standard Python asks and I couldn't find a user guide on how to use this script. Forgive me if I'm missing something obvious

**Comment by wesleyw72** [comment]
You don't need to run converter.py, there are already converted models provided in a submodule.

Look [here](https://github.com/NVIDIA/FastPhotoStyle/blob/master/USAGE.md), this shows the steps to perform the transfer. I can confirm that it will work fine on macOS, give it a go and let us know if you get stuck.

**Comment by wesleyw72** [comment]
@fabulousrice You do not need CUDA capable hardware to get most of the effect, the only part you'll be missing is the final smoothing step which will still give you the majority of the effect. I am running it on a MacBook Pro (late 2016). Please could you describe the errors/problems you are facing and I will try to help.

**Comment by learncss** [comment]
Could you give all the steps you did to make this work on macOS? I am having a difficult time with it.

**Comment by djenryte** [comment]
Took a while, but I got this project running on osx 10.12.6 using CUDA 9.1 and cuDNN 7.0.5. 

The project makes use of the torch.svd() function of pytorch so you'll need to install magma-cuda9.1. Since an osx version doesn't exist on the conda repo, `conda install magma-cuda90 -c soumith` won't work. You'll need to build/install it locally by cloning from: https://github.com/pytorch/builder/tree/master/conda/magma-cuda91-2.3.0

Then running:
```
conda install -y conda-build
. ./switch_cuda_version.sh 9.1
conda build magma-cuda91-2.3.0
conda install --use-local magma-cuda91
```

**Comment by learncss** [comment]
I'm not able to get . ./switch_cuda_version.sh 9.1 to run. Any ideas? It says 
-bash: ./switch_cuda_version.sh: No such file or directory

**Comment by learncss** [comment]
Actually, could you please write down all steps from beginning to end on getting it working on a mac? I am not even sure how your code earlier works in with the original instructions. I need to get this working for a project soon and I'm at a loss.

**Comment by gaoyangyiqiao** [comment]
Hi,when I run `python demo.py --cuda 0` I met a problem like this:
```
cont_seg = torch.FloatTensor(np.asarray(cont_seg))
RuntimeError: the given numpy array has zero-sized dimensions. Zero-sized dimensions are not supported in PyTorch
```
Does this mean that there is some problem with my pytorch version?
I am using Macos 10.13 and pytorch version is 0.3.
@wesleyw72 @djenryte

**Comment by mingyuliutw** [comment]
@gaoyangyiqiao We temporally rolled back to the previous commit. It should work now.
