### ISSUE TITLE
ValueError: total size of new array must be unchanged

### ISSUE THREAD

**Issue by Instagit** [NVIDIA/FastPhotoStyle#43]
What am I doing wrong? The simple demo with global style works, but trying with label maps I get an error.

Picture of the images and the visualized label maps:
![fps](https://user-images.githubusercontent.com/2681794/38022667-69575d90-3280-11e8-82dc-d5713fbc10cc.png)

I run this command:

````shell
python demo.py \
--content_image_path images/custom2/content1.png \
--content_seg_path images/custom2/content1.label/label.png \
--style_image_path images/custom2/style1.png \
--style_seg_path images/custom2/style1.label/label.png \
--output_image_path results/example2.png
````

Output and error:

````log
Elapsed time in stylization: 0.417996
Traceback (most recent call last):
  File "demo.py", line 43, in <module>
    cuda=args.cuda,
  File "/home/ubuntu/.fast-photo-style/process_stylization.py", line 62, in stylization
    stylized_img = p_wct.transform(cont_img, styl_img, cont_seg, styl_seg)
  File "/home/ubuntu/.fast-photo-style/photo_wct.py", line 35, in transform
    csF4 = self.__feature_wct(cF4, sF4, cont_seg, styl_seg)
  File "/home/ubuntu/.fast-photo-style/photo_wct.py", line 88, in __feature_wct
    cont_mask = np.where(t_cont_seg.reshape(t_cont_seg.shape[0] * t_cont_seg.shape[1]) == l)
ValueError: total size of new array must be unchanged
````

**Comment by wesleyw72** [comment]
Can you double check that images/custom2/content1.png and images/custom2/content1.label/label.png are the same dimensions?

**Comment by Yijunmaverick** [comment]
@Instagit Thanks for your interests.

Your mask looks like a 3-label mask but I do not see what "0" means here. I think you can draw a 2-label map, i.e., drawing a polygon for the sky and leaving the rest as non-sky. Similar to your masks, I draw a 2-label map and obtain the transfer result:

![in156](https://user-images.githubusercontent.com/10704714/38044594-1a398f00-326f-11e8-9553-eeef130d9d88.png)

My label maps:

![label_viz](https://user-images.githubusercontent.com/10704714/38044568-0867230a-326f-11e8-8eba-a5970cc0eeca.png)

![label_viz](https://user-images.githubusercontent.com/10704714/38044581-11732872-326f-11e8-824b-c3ea297d102e.png)

Hope you like it.

**Comment by Instagit** [comment]
Yijunmaverick thanks for your efforts! The label **0: background** is automatically added when I run ````labelme_json_to_dataset content1.json -o content1.label````.

I created label maps very similar to yours, but still get the same error. All images have the same dimensions, in this case 1080x608px.

![label_viz](https://user-images.githubusercontent.com/2681794/38080142-fa121a3a-3340-11e8-895f-bb7a5e5da815.png)
![label_viz](https://user-images.githubusercontent.com/2681794/38080149-fcfa95ba-3340-11e8-9178-3c5cf32e3769.png)

````
Elapsed time in stylization: 0.816283
Traceback (most recent call last):
  File "demo.py", line 43, in <module>
    cuda=args.cuda,
  File "/home/ubuntu/.fast-photo-style/process_stylization.py", line 62, in stylization
    stylized_img = p_wct.transform(cont_img, styl_img, cont_seg, styl_seg)
  File "/home/ubuntu/.fast-photo-style/photo_wct.py", line 35, in transform
    csF4 = self.__feature_wct(cF4, sF4, cont_seg, styl_seg)
  File "/home/ubuntu/.fast-photo-style/photo_wct.py", line 88, in __feature_wct
    cont_mask = np.where(t_cont_seg.reshape(t_cont_seg.shape[0] * t_cont_seg.shape[1]) == l)
ValueError: total size of new array must be unchanged
````

Are there tests I can run to make sure the project and dependencies are set up correctly?

**Comment by Instagit** [comment]
@Yijunmaverick That did it. Thank you!

**Comment by Yijunmaverick** [comment]
@Instagit Regarding the label `0`, you're right. The `labelme` tool will automatically label all pixels that we do not label as `0`. This generally happens between two adjacent masks as we cannot accurately label each pixel and will often miss a few ones on the boundary. My suggestion is that when you are drawing masks, you can let them have some small overlaps to avoid this. Thanks to the pixel affinity employed in our algorithm (the 2nd propagation step), the roughly drawn masks are already enough for generating a good result.
