### ISSUE TITLE
Whitening

### ISSUE THREAD

**Issue by wesleyw72** [NVIDIA/FastPhotoStyle#44]
I am slightly confused by the whitening step. In your reference [[14]](https://www.projectrhea.org/rhea/images/1/15/Slecture_ECE662_Whitening_and_Coloring_Transforms_S14_MH.pdf) it seems to have a slightly different equation for whitening. 

It translates to removing the {E_s} term from your equation for {P_s}. I don't understand why you have the {E_s} at the start of this, could you explain? It seems as if you are scaling by the orthonormal eigenvector matrix.

There is a similar observation in the coloring step.
Thanks!

**Comment by Yijunmaverick** [comment]
@wesleyw72 That's the difference between ZCA (I used) and PCA whitening. Take a look at this [discussion](https://stats.stackexchange.com/questions/117427/what-is-the-difference-between-zca-whitening-and-pca-whitening). Both are the same for just whitening, but `ZCA-whitened images still resemble normal images`. I guess that's what `Z` means (zero-phase).

**Comment by wesleyw72** [comment]
Thank you, that makes sense.
