### ISSUE TITLE
ValueError: unknown file extension

### ISSUE THREAD

**Issue by Hunterwolf88** [NVIDIA/FastPhotoStyle#47]
fixed the "cannot reshape array..." following this: https://github.com/NVIDIA/FastPhotoStyle/issues/36

But now running
`python demo.py --content_image_path ./images/content1.png --content_seg_path ./images/labelc/label.png --style_image_path ./images/style1.png --style_seg_path ./images/labels/label.png --output_image_path ./results`

I get
`ValueError: unknown file extension: `

**Comment by wesleyw72** [comment]
Give your output_image_path an extension. e.g. --output_image_path ./results/out.png

**Comment by Hunterwolf88** [comment]
oh that was so dumb :D thanks!
