### ISSUE TITLE
not able to run my docker with nvidia runtime

### ISSUE THREAD

**Issue by pankajniet** [NVIDIA/FastPhotoStyle#50]
docker run -v /home:/home --runtime=nvidia -i -t your-docker-image:v1.0 /bin/bash
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig --device=all --compute --utility --require=cuda>=9.0 --pid=8878 /var/lib/docker/devicemapper/mnt/aae876e5f0e27dc382e77bbc397f6bf5ced6649656681151fe6e397c2c52ebee/rootfs]\\\\nnvidia-container-cli: initialization error: driver error: failed to process request\\\\n\\\"\"": unknown.

**Comment by issamsaid** [comment]
---> Using cache
 ---> e292f3342280
Step 8/16 : RUN wget https://repo.continuum.io/archive/Anaconda3-5.0.1-Linux-x86_64.sh -P /tmp
 ---> Using cache
 ---> 908888e7eea3
Step 9/16 : RUN bash /tmp/Anaconda3-5.0.1-Linux-x86_64.sh -b -p $ANACONDA
 ---> Using cache
 ---> 6fe970168862
Step 10/16 : RUN rm /tmp/Anaconda3-5.0.1-Linux-x86_64.sh -rf
 ---> Using cache
 ---> a42e65598ca2
Step 11/16 : RUN conda install -y pytorch=0.4.1 torchvision cuda91 -c pytorch
 ---> Using cache
 ---> b5ea1f82c7ec
Step 12/16 : RUN conda install -y -c anaconda pip
 ---> Running in 68d2ae1c19dd
Collecting package metadata: ...working... done
Solving environment: ...working... 

is it normal that solving env takes forever?
