### ISSUE TITLE
Failed with UMFPACK_ERROR_out_of_memory

### ISSUE THREAD

**Issue by ycjing** [NVIDIA/FastPhotoStyle#52]
Thanks for the great code. When I run the algorithm with my own high-resolution images (655 * 1280), I find that when using scipy.sparse.linalg.spsolve with scikit-umfpack as solver, it requires too much memory (larger than 128GB). 
After some investigations, I found the problem might be OS dependent. However, I actually followed the instructions: my OS is Ubuntu 16.04, also the same CUDA and python version.
 
I wonder if anyone struggles at the same issue with me, and if there is any other solver. Thanks.

**Comment by wesleyw72** [comment]
Try uninstalling scikit-umfpack (with pip). I sometimes found the default sparse solver could handle larger images. You will find it's considerably slower though.

**Comment by ycjing** [comment]
@wesleyw72 Thanks! But it is far too slow, especially for high-resolution images  :(

**Comment by Yijunmaverick** [comment]
@ycjing Thanks for your interests.

You can check this [work](http://delivery.acm.org/10.1145/2010000/2009988/p525-xu.pdf?ip=169.236.182.209&id=2009988&acc=ACTIVE%20SERVICE&key=CA367851C7E3CE77%2E21EA8071FB88D747%2E4D4702B0C3E38B35%2E4D4702B0C3E38B35&__acm__=1525287003_7c715a0c1ac726f9c7c47efa27be92aa) which will reduce the N*N (N is the number of pixels) adjacent matrix `W` to k*k for efficiency. High-res is always a challenging issue.

**Comment by ycjing** [comment]
@Yijunmaverick Really appreciate the help! Thanks!

**Comment by 785256592** [comment]
> @Yijunmaverick Really appreciate the help! Thanks!

dear@ycjing  I also have this problem ,can you show me how to handle it ! very thanks!
BTW

**Comment by ycjing** [comment]
Hi @785256592 ,

Since it has been almost two years since I worked on this project, I hardly remember the problem and the solution. Really sorry for that.

**Comment by Dominoer** [comment]
> > @Yijunmaverick Really appreciate the help! Thanks!
> 
> dear@ycjing I also have this problem ,can you show me how to handle it ! very thanks!
> BTW

In my case, simply uninstalling scikit-umfpack worked.

**Comment by doantientai** [comment]
> > > @Yijunmaverick Really appreciate the help! Thanks!
> > 
> > 
> > dear@ycjing I also have this problem ,can you show me how to handle it ! very thanks!
> > BTW
> 
> In my case, simply uninstalling scikit-umfpack worked.

Thank you! Uninstalling scikit-umfpack worked for me too.
