### ISSUE TITLE
Incorrect  Anaconda version in Dockerfile

### ISSUE THREAD

**Issue by 01010101** [NVIDIA/FastPhotoStyle#60]
RUN wget https://repo.continuum.io/archive/Anaconda2-5.0.1-Linux-x86_64.sh -P /tmp

Should be

RUN wget https://repo.continuum.io/archive/Anaconda3-5.0.1-Linux-x86_64.sh -P /tmp

**Comment by 01010101** [comment]
Pull request https://github.com/NVIDIA/FastPhotoStyle/pull/61

**Comment by mingyuliutw** [comment]
@01010101 Thanks. I have fixed the issue and a couple of other related issues in the latest commit.
