### ISSUE TITLE
Can I only transfer the image with only L band?  

### ISSUE THREAD

**Issue by Jiajia0319** [NVIDIA/FastPhotoStyle#65]
The max size I can transfer now is 960, in order to transfer larger image, can I transfer it with L band than add ab band to get the final result? 
Thanks a lot!!

**Comment by Yijunmaverick** [comment]
Thanks for your interests. Currently, the model only accepts a 3-channel input so you also need to replicate your L channel 3 times before feeding it into the model. So I think the image size is still limited. High-res is always a challenging issue to deep models.
