### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './models/vgg_normalised_conv1_1_mask.t7'

### ISSUE THREAD

**Issue by ebrahimkarimi** [NVIDIA/FastPhotoStyle#66]
Hello
sorry i'm new to machine learning and image processing, when i was following [Tutorial](https://github.com/NVIDIA/FastPhotoStyle/blob/master/TUTORIAL.md) i faced this issue
`Traceback (most recent call last):
  File "./demo.py", line 30, in <module>
    p_wct = PhotoWCT(args)
  File "/media/<User>/Data/Knowledeg/SourceCodes/Nvidia/Python/FastPhotoStyle/photo_wct.py", line 18, in __init__
    vgg1 = load_lua(args.vgg1)
  File "/home/<User>/anaconda3/lib/python3.6/site-packages/torch/utils/serialization/read_lua_file.py", line 606, in load_lua
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './models/vgg_normalised_conv1_1_mask.t7'`
Note that i'm using Cuda 9.2 and pytorch 0.4.0 and Anaconda3 on Ubuntu 18.04.1 LTS

**Comment by Yijunmaverick** [comment]
Thanks for you interests. It looks that you're using the older version of our code. We have integrated all models together under `./PhotoWCTModels/`.

You can also download the original models [here](https://drive.google.com/file/d/1ENgQm9TgabE1R99zhNf5q6meBvX6WFuq/edit) to run the older version.
