### ISSUE TITLE
Couldn't Reproduce the Results

### ISSUE THREAD

**Issue by KangBK0120** [NVIDIA/FastPhotoStyle#67]
Hi, I found the same images(content and style) which you used in the paper to reproduce your results.

However, when I ran your codes, I couldn't get the result similar to yours.

Is there anything I missed?

![image](https://user-images.githubusercontent.com/25279765/46934750-deb56580-d093-11e8-8bc2-592bdb1854d7.png)

**Comment by Yijunmaverick** [comment]
Thanks for your interests. This looks like a global transferring result, as shown in `Example 1` of the tutorial. As mentioned in our paper, to achieve the best and reasonable result, we use masks to determine the correspondence (e.g., sky-to-sky, house-to-house) for most of times. Check `Example 2` in our tutorial. For this example, we draw a mask with 3 labels for sky, house and ground. You can determine your own correspondence, as a kind of user control.
