### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by xerebz** [NVIDIA/FastPhotoStyle#7]
Please add a Dockerfile that creates an image with the program inside, ready to execute.

**Comment by borisfom** [comment]
Docker image would definitely exceed the 150MB size Github limit, but Dockerfile would be nice! Especially if you provide one that would use  NVIDIA DGX container for PyTorch as the base.

**Comment by xerebz** [comment]
Thanks @borisfom I've updated the issue.

**Comment by xerebz** [comment]
One of the CUDA 9.1 + Ubuntu 16.04 Dockerfiles on Nvidia's hub would be a good starting point. https://hub.docker.com/r/nvidia/cuda/

**Comment by mingyuliutw** [comment]
Dockerfile added. 

USAGE.md updated with a simple usage example.

**Comment by t0mst0ne** [comment]
Hi:

I build the docker successfully and then I got error when execute 

sudo docker run -v /home/root:/opt --runtime=nvidia -i -t fastphotostyle:v1.0 /bin/bash

docker: Error response from daemon: Unknown runtime specified nvidia.

Question : Should I also run nvidia images ? and which one ? 

Thanks

**Comment by mingyuliutw** [comment]
I forgot to specify that you need to install nvidia-docker first. Please follow the instruction in https://github.com/NVIDIA/nvidia-docker

**Comment by t0mst0ne** [comment]
@mingyuliutw   thanks , but I just found that the nvidia-docker2 needs to be installed from docker-ce rather then previous (sudo apt install docker.io) ; so need to remove what had been just builded. Maybe need mention docker version and dependence ? 

Many thanks for the repo !

**Comment by mingyuliutw** [comment]
Thanks for the suggestion. Yes, I will specify the docker version in the next commit.

**Comment by kmader** [comment]
we made a binder-ready version here: https://github.com/4QuantOSS/FastPhotoStyle you can then use jupyter repo2docker to make a dockerfile if you want

**Comment by borisfom** [comment]
Thanks guys, I will try!

**Comment by xerebz** [comment]
Thanks @mingyuliutw, this Dockerfile worked perfectly.
