### ISSUE TITLE
License/Copyright for matting laplacian

### ISSUE THREAD

**Issue by MarcoForte** [NVIDIA/FastPhotoStyle#72]
Hi I'm not intimately familiar with code licensing but I'd like to point out that in https://github.com/NVIDIA/FastPhotoStyle/blob/master/photo_smooth.py
you are using my code for the `__compute_laplacian` function. 
See here , 
https://github.com/MarcoForte/closed-form-matting/blob/master/closed_form_matting.py
It seems you've claimed copyright over it. My code is [MIT licensed](https://choosealicense.com/licenses/mit/) so you are free to use it but could you attribute me please.
Thanks

**Comment by mingyuliutw** [comment]
@MarcoForte Sorry that I didn't know the code was borrowed from your repo. To fix it, I have added comments to point out the source in the new commit. Thanks again for sharing the code.

**Comment by MarcoForte** [comment]
Thanks!
